# Default values
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

ServiceType: NodePort
Image: hub.tigerobo.com:88/tigerobo/vue-front
Imagetag: 'latest'
Replicas: 1
ImagePullPolicy: "Always"
Cpu: "10m"
Memory: "128Mi"
ContainerPort: 80
ServicePort: 80
DomainName: vue-front
