# Default values
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

ServiceType: NodePort

Name: vue-front

image:
  repository: hub.tigerobo.com:88/tigerobo/vue-front
  tag: latest
  pullPolicy: IfNotPresent

Replicas: 2
Cpu: "10m"
Memory: "128Mi"
ContainerPort: 80
ServicePort: 80
DomainName: vue-front
