apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "vue-front.full_name" . }}
  labels:
    {{- include "vue-front.release_labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.Replicas }}
  template:
    metadata:
      labels:
        {{- include "vue-front.release_labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.ContainerPort}}
              protocol: TCP
          resources:
            requests:
              cpu: "{{.Values.Cpu}}"
              memory: "{{.Values.Memory}}"
