apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "springboot-helm.full_name" . }}
  labels: 
    {{- include "springboot-helm.release_labels" . | indent 4 }}
spec:
  rules:
  - host: {{.Values.DomainName}}.buyabs.corp
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "springboot-helm.full_name" . }}
          servicePort: {{.Values.ContainerPort}}
